### ISSUE TITLE
Scrub AndcultureCode from C# Repo

### ISSUE THREAD

**Issue by rllowman** [rsm-hcd/RSM.HCD.CSharp#55]
Replace all instances of `andculture` and `AndcultureCode` with RSM HCD

Common Replacements
- GitHub Organization: `rsm-hcd`
- NuGet Organization: `rsm-hcd`
- Namespace Prefix: `RSM.HCD`
- Assembly Name Prefix: `RSM.HCD`
- Package Name Prefix: `RSM.HCD`
- Email: `HCD-Team-Developer@rsmus.com`

**Comment by myty** [comment]
`andcli` is the last remaining holdout but is handled with #59
